#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# install required packages on all nodes part of the cloud
 - hosts: resources
   become: yes
   roles:
     - stig-compliant
   tasks:
     - include: roles/stig-compliant/tasks/install_pkgs.yml 
     - include: roles/stig-compliant/tasks/stig_config.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000004-GPOS-00004.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000005-GPOS-00005.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000006-GPOS-00006.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000021-GPOS-00005.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000027-GPOS-00008.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000029-GPOS-00010.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000033-GPOS-00014.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000042-GPOS-00020.yml 
     - include: roles/stig-compliant/tasks/SRG-OS-000420-GPOS-00186.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000471-GPOS-00216.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000474-GPOS-00219.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000109-GPOS-00056.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000118-GPOS-00060.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000185-GPOS-00079.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000205-GPOS-00083.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000215-GPOS-00085.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000250-GPOS-00093.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000254-GPOS-00095.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000344-GPOS-00135.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000047-GPOS-00023.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000062-GPOS-00031.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000064-GPOS-00033.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000074-GPOS-00042.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000075-GPOS-00043.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000076-GPOS-00044.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000480-GPOS-00226.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000021-GPOS-00005.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000055-GPOS-00026.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000095-GPOS-00049.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000080-GPOS-00048.yml
     - include: roles/stig-compliant/tasks/SRG-OS-000096-GPOS-00050.yml
     - include: roles/stig-compliant/tasks/password_requirements.yml

