#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

  - name: Find | SETUID files| Find SETUID files in /
    become: yes
    shell:
      find /  -xdev -type f -perm -4000 -o -type f -perm -2000
    tags: srg-setuid
    register: srg_setuid
    changed_when: srg_setuid.stdout == ""

  - name: Update | Config | Add SETUID executables to audit.rules
    lineinfile:
      dest: /etc/audit/audit.rules
      line: '-a always,exit -F path={{ item }} -F perm=x -F auid>=500 -F auid!=4294967295 -k privileged_command'
      #backrefs: yes
    with_items:
      - "{{ srg_setuid.stdout_lines }}"
    tags: srg-sshciphers

