#
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---


- name: SRG-OS-000047-GPOS-00023 | deploy | system must shut down by default upon audit failure
  become: yes
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: '^space_left ='
    line: "space_left = {{ aud_space_left }}"
  notify:
    - Reload audit rules


- name: SRG-OS-000047-GPOS-00023 | deploy | set space_left_action
  become: yes
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: '^space_left_action ='
    line: "space_left_action = {{ aud_space_left_act }}"
  notify:
    - Reload audit rules


- name: SRG-OS-000047-GPOS-00023 | deploy | set admin_space_left
  become: yes
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: '^admin_space_left ='
    line: "admin_space_left = {{ aud_admin_space_left }}"
  notify:
    - Reload audit rules


- name: SRG-OS-000047-GPOS-00023 | deploy | set disk_full_action
  become: yes
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: '^disk_full_action ='
    line: "disk_full_action = {{ aud_disk_full_act }}"
  notify:
    - Reload audit rules


- name: SRG-OS-000047-GPOS-00023 | deploy | set admin_space_left_action
  become: yes
  lineinfile: 
    dest: /etc/audit/auditd.conf
    regexp: '^admin_space_left_action ='
    line: "admin_space_left_action = {{ adm_space_left_act }}"
  notify:
    - Reload audit rules



- name: SRG-OS-000047-GPOS-00023 | deploy | set disk_error_action
  become: yes
  lineinfile: 
    dest: /etc/audit/auditd.conf
    regexp: '^disk_error_action ='
    line: "disk_error_action = {{ disk_err_act }}"
  notify:
    - Reload audit rules
