#
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#


---

  - name: SRG-OS-000338-GPOS-00130 | deploy | log user sessions
    become: yes
    lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\*\.\*;auth,authpriv.none'
      line: "*.*;auth,authpriv.none,local6           -/var/log/syslog"


  - name: SRG-OS-000338-GPOS-00130 | deploy | set logfile for user sessions
    become: yes
    lineinfile: 
      dest: /etc/rsyslog.conf
      regexp: '^local6.info'    
      line: "local6.info		/var/log/history.log"


  - name: SRG-OS-000338-GPOS-00130 | deploy | ensure logfile exists
    stat:
      path: /var/log/history.log
    register: hist_file

  - name: SRG-OS-000338-GPOS-00130 | deploy | create logfile if it doesn't exist
    become: yes
    file:
      dest: /var/log/history.log
      owner: root
      group: root    
      mode: 0644
      state: touch
    when: hist_file.stat.exists != True


  - name: SRG-OS-000338-GPOS-00130 | deploy | restart rsyslog service if logfile didn't exist
    become: yes
    service:
      name: rsyslog
      state: restarted
    when: hist_file.stat.exists != True
