#
# (c) Copyright 2016 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: SRG-OS-000064-GPOS-00033 | deploy | ensure /etc/sudoers is being audited
  become: yes
  lineinfile:
    dest: /etc/audit/audit.rules
    line: "-w /etc/sudoers -p wa -k access_sudoers"
  notify:
    - Reload audit rules



- name: SRG-OS-000064-GPOS-00033 | deploy | b32 -EACCES
  become: yes
  lineinfile:
    dest: /etc/audit/audit.rules
    line: "-a always,exit -F arch=b32 -S open -S openat -F exit=-EACCES -k access_permissions"
  notify:
    - Reload audit rules




- name: SRG-OS-000064-GPOS-00033 | deploy | b32 -EPERM
  become: yes
  lineinfile:
    dest: /etc/audit/audit.rules
    line: "-a always,exit -F arch=b32 -S open -S openat -F exit=-EPERM -k access_permissions"
  notify:
    - Reload audit rules




- name: SRG-OS-000064-GPOS-00033 | deploy | b64 -EACCES
  become: yes
  lineinfile:
    dest: /etc/audit/audit.rules
    line: "-a always,exit -F arch=b64 -S open -S openat -F exit=-EACCES -k access_permissions"
  notify:
    - Reload audit rules




- name: SRG-OS-000064-GPOS-00033 | deploy | b64 -EPERM
  become: yes
  lineinfile:
    dest: /etc/audit/audit.rules
    line: "-a always,exit -F arch=b64 -S open -S openat -F exit=-EPERM -k access_permissions"
  notify:
    - Reload audit rules




